version: '3'
services:
  yacyag-ui:
    image: docker.jvoj.cz/yacyag-ui:latest
  yacyag-be:
    depends_on:
      - mongo
    image: docker.jvoj.cz/yacyag-be:latest
    volumes:
      - /docker_volumes/gear.print.jvoj.cz/be:/usr/src/app/images
      - ./fe.env:/usr/src/app/.env
  mongo:
    image: mongo
    volumes:
      - /docker_volumes/gear.print.jvoj.cz/mongo:/data/db
  nginx:
    build: ./nginx
    depends_on:
      - yacyag-be
      - yacyag-ui
    environment:
      - VIRTUAL_HOST=gear.print.jvoj.cz
      - LETSENCRYPT_HOST=gear.print.jvoj.cz
      - LETSENCRYPT_EMAIL=vojira@gmail.com
      - VIRTUAL_PORT=80
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 8080:80
networks:
  gear.print.jvoj.cz:
    external:
      name: gear.print.jvoj.cz
